services:
  kali-builder:
    image: kalilinux/kali-rolling
    container_name: kali-iso-builder
    volumes:
      - .:/workdir
    working_dir: /workdir
    privileged: true
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        export DEBIAN_FRONTEND="noninteractive"
        apt update
        apt upgrade -y 
        apt install -y git live-build simple-cdd cdebootstrap curl
        chmod +x ./build.sh
        ./build.sh --verbose
        #cp /workdir/*.iso /workdir/output/
    stdin_open: true
    tty: true
