name: Build Kali ISO

on:
  workflow_dispatch:  # This will trigger the workflow manually

jobs:
  build:
    runs-on: ubuntu-latest  # You can change this to another runner if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Build Kali ISO using Docker
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE:/workdir \
            --workdir /workdir \
            --privileged \
            kalilinux/kali-rolling \
            bash -c "
              export DEBIAN_FRONTEND='noninteractive' && \
              apt update && \
              apt upgrade -y && \
              apt install -y git live-build simple-cdd cdebootstrap curl && \
              chmod +x ./build.sh && \
              ./build.sh --verbose
            "
      - name: Save output ISO to artifacts
        uses: actions/upload-artifact@v4
        with:
           name: iso-output
           path: ./images/*
